[build]
  command = "npm install && npx tsc && vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  VITE_SUPABASE_DATABASE_URL = ""
  VITE_TURSO_DATABASE_URL = ""
  VITE_TURSO_AUTH_TOKEN = ""
  AUTH0_CLIENT_ID = ""
  AUTH0_AUDIENCE = ""