[build]
  command = "npm install && chmod +x deploy.sh && ./deploy.sh"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Netlify Functions redirects are handled automatically by Netlify

[build.environment]
  NODE_ENV = "production"
  # Empty environment variables - these will be set in the Netlify dashboard
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  VITE_SUPABASE_DATABASE_URL = ""
  VITE_AUTH0_CLIENT_ID = ""
  VITE_AUTH0_AUDIENCE = ""
  VITE_AUTH0_DOMAIN = ""
  # Disable secrets scanning
  SECRETS_SCAN_ENABLED = "false"

# We'll use Netlify's built-in functionality instead of custom plugins

# Security headers are now defined in the _headers file